// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {application} from '../models';

export function AutoIndexGames():Promise<void>;

export function Create(arg1:desktop.CreateInputDto):Promise<Array<string>>;

export function CreateDesktopShortcut(arg1:desktop.GetInputDto):Promise<void>;

export function Get(arg1:desktop.GetInputDto):Promise<application.GetGameOutput>;

export function GetPlatformTypes():Promise<Array<string>>;

export function List(arg1:desktop.ListInputDto):Promise<Array<application.ListGamesOutput>>;

export function StartGame(arg1:desktop.GetInputDto):Promise<void>;

export function Update(arg1:desktop.UpdateInputDto):Promise<Array<string>>;
