// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoIndexGames() {
  return window['go']['desktop']['GameController']['AutoIndexGames']();
}

export function Create(arg1) {
  return window['go']['desktop']['GameController']['Create'](arg1);
}

export function CreateDesktopShortcut(arg1) {
  return window['go']['desktop']['GameController']['CreateDesktopShortcut'](arg1);
}

export function Get(arg1) {
  return window['go']['desktop']['GameController']['Get'](arg1);
}

export function GetPlatformTypes() {
  return window['go']['desktop']['GameController']['GetPlatformTypes']();
}

export function List(arg1) {
  return window['go']['desktop']['GameController']['List'](arg1);
}

export function StartGame(arg1) {
  return window['go']['desktop']['GameController']['StartGame'](arg1);
}

export function Update(arg1) {
  return window['go']['desktop']['GameController']['Update'](arg1);
}
