// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {desktop} from '../models';

export function Get():Promise<application.GetSettingsOutput>;

export function Save(arg1:desktop.SaveSettingsInputDto):Promise<string>;
