FROM ubuntu:latest
RUN apt update
RUN apt install wget -y
RUN apt install nodejs -y
RUN apt install npm -y
RUN apt install make -y
RUN apt install libgtk-3-dev -y
RUN apt install libwebkit2gtk-4.1-dev -y
RUN apt install golang -y
RUN go install github.com/wailsapp/wails/v2/cmd/wails@latest
RUN cp /root/go/bin/wails /usr/local/bin/wails
RUN apt install xvfb -y
RUN apt install dbus-x11 -y

RUN useradd -m -s /bin/bash appuser

WORKDIR /retrolauncher
COPY . .
RUN chown -R appuser:appuser /retrolauncher

USER appuser

EXPOSE 5173
ENTRYPOINT ["sh"]