FROM golang:latest
RUN echo -e "\nTypes: deb\nURIs: http://gb.archive.debian.org/debian\nSuites: bookworm\nComponents: main\nSigned-By: /usr/share/keyrings/debian-archive-keyring.gpg" >> /etc/apt/sources.list.d/debian.sources
RUN apt update
RUN apt install nodejs -y
RUN apt install npm -y
RUN apt install make -y
RUN apt install libgtk-3-dev -y
RUN apt install libwebkit2gtk-4.1-dev -y
RUN go install github.com/wailsapp/wails/v2/cmd/wails@latest
RUN apt install xvfb -y
RUN apt install dbus-x11 -y
WORKDIR /app
COPY . .
EXPOSE 5173
ENTRYPOINT ["sh"]