services:
  app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app
    container_name: "retrolauncher_dev_env"
    stdin_open: true
    tty: true
    entrypoint: ["sh"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
