// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {platform_controller} from '../models';

export function Create(arg1:platform_controller.CreateInputDto):Promise<Array<Error>>;
