// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['platform_controller']['PlatformController']['Create'](arg1);
}

export function GetPlatformTypes() {
  return window['go']['platform_controller']['PlatformController']['GetPlatformTypes']();
}
