// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {platform_controller} from '../models';
import {list_platforms} from '../models';

export function Create(arg1:platform_controller.CreateInputDto):Promise<Array<Error>>;

export function GetPlatformTypes():Promise<Array<string>>;

export function List():Promise<Array<list_platforms.Output>>;
