// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game_controller} from '../models';
import {get_game} from '../models';
import {list_games} from '../models';

export function Create(arg1:game_controller.CreateInputDto):Promise<Array<string>>;

export function Get(arg1:game_controller.GetInputDto):Promise<get_game.Output>;

export function GetPlatformTypes():Promise<Array<string>>;

export function List(arg1:game_controller.ListInputDto):Promise<Array<list_games.Output>>;

export function StartGame(arg1:game_controller.GetInputDto):Promise<void>;

export function Update(arg1:game_controller.UpdateInputDto):Promise<void>;
