// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoIndexGames() {
  return window['go']['game_controller']['GameController']['AutoIndexGames']();
}

export function Create(arg1) {
  return window['go']['game_controller']['GameController']['Create'](arg1);
}

export function Get(arg1) {
  return window['go']['game_controller']['GameController']['Get'](arg1);
}

export function GetPlatformTypes() {
  return window['go']['game_controller']['GameController']['GetPlatformTypes']();
}

export function List(arg1) {
  return window['go']['game_controller']['GameController']['List'](arg1);
}

export function StartGame(arg1) {
  return window['go']['game_controller']['GameController']['StartGame'](arg1);
}

export function Update(arg1) {
  return window['go']['game_controller']['GameController']['Update'](arg1);
}
