// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game_controller} from '../models';
import {list_games} from '../models';

export function Create(arg1:game_controller.CreateInputDto):Promise<void>;

export function List(arg1:game_controller.ListInputDto):Promise<Array<list_games.Output>>;

export function Update(arg1:game_controller.UpdateInputDto):Promise<void>;
