// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['game_controller']['GameController']['Create'](arg1);
}

export function List(arg1) {
  return window['go']['game_controller']['GameController']['List'](arg1);
}

export function Update(arg1) {
  return window['go']['game_controller']['GameController']['Update'](arg1);
}
